### ISSUE TITLE
Dataset container shouldn't be mounted to host machine

### ISSUE THREAD

**Issue by IakMastro** [IakMastro/Revelations#3]
# Problem

Right now, the docker instance of the host machine is mounted directly to the container. This could be really bad in an attack because the attacker could assume root access to the system via the container.  This weird bug exists ONLY in the docker-compose file and it doesn't exist if it's run with ``docker run``.

## What should be deleted

```yaml

  docker-api:
    build: docker-api
    container_name: docker-management-api
    hostname: docker-api
    depends_on:
      - fluentd
    volumes:
      - ./docker-api:/api
      - ./data/files:/files
      - /var/run/docker.sock:/var/run/docker.sock # This one
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224
        tag: log.docker
    networks:
      - revelations-net
```

This could solve the crash that happens on the API and make it dynamic.
